/** Health Tracker V1 — local-first, single-user. */
(function () {
  'use strict';

  var TZ = 'Asia/Bangkok';
  var KEYS = { weight:'ht_weight', exercise:'ht_exercise', food:'ht_food', settings:'ht_settings', programs:'ht_programs', mealRoutines:'ht_meal_routines' };
  var currentTab = 'today';
  var foodPhotoData = null;
  var selectedFoodBase = null;
  var programDraft = [];
  var mealRoutineDraft = [];
  var activeWorkoutId = null;
  var shiftContext = null;
  var timerSeconds = 0;
  var timerHandle = null;

  function $(id) { return document.getElementById(id); }
  function esc(value) { return String(value == null ? '' : value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;'); }
  function enc(value) { return encodeURIComponent(String(value)); }
  function dec(value) { try { return decodeURIComponent(value); } catch (_) { return value; } }
  function uid(prefix) { return prefix + '_' + Date.now() + '_' + Math.random().toString(36).slice(2,8); }
  function num(value, min, max, fallback) { var n=Number(value); return !Number.isFinite(n)||(min!=null&&n<min)||(max!=null&&n>max) ? fallback : n; }
  function sum(list, field) { return list.reduce(function (n,item) { return n+num(item[field],null,null,0); },0); }
  function pct(value, goal) { return goal>0 ? Math.max(0,Math.min(100,value/goal*100)) : 0; }
  function dateTimeKey(record) { return (record.date||'')+'T'+(record.time||'00:00'); }

  function today() {
    var out={};
    new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).forEach(function(p){out[p.type]=p.value;});
    return out.year+'-'+out.month+'-'+out.day;
  }
  function timeNow() {
    var out={};
    new Intl.DateTimeFormat('en-GB',{timeZone:TZ,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).forEach(function(p){out[p.type]=p.value;});
    return out.hour+':'+out.minute;
  }
  function shiftDate(dateStr, amount) {
    var p=String(dateStr).split('-').map(Number), d=new Date(Date.UTC(p[0],p[1]-1,p[2]+amount));
    return d.getUTCFullYear()+'-'+String(d.getUTCMonth()+1).padStart(2,'0')+'-'+String(d.getUTCDate()).padStart(2,'0');
  }
  function weekStart(dateStr) {
    var p=dateStr.split('-').map(Number), day=new Date(Date.UTC(p[0],p[1]-1,p[2])).getUTCDay();
    return shiftDate(dateStr,-(day===0?6:day-1));
  }
  function displayDate(dateStr, weekday) {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(dateStr||'')) return '—';
    return new Date(dateStr+'T00:00:00+07:00').toLocaleDateString('th-TH',{timeZone:TZ,weekday:weekday?'short':undefined,day:'numeric',month:'short',year:'numeric'});
  }

  function readJson(key, fallback) {
    var raw=localStorage.getItem(key); if(!raw) return fallback;
    try {
      var parsed=JSON.parse(raw);
      if(Array.isArray(fallback)&&!Array.isArray(parsed)) throw new Error('array expected');
      if(!Array.isArray(fallback)&&(parsed==null||typeof parsed!=='object'||Array.isArray(parsed))) throw new Error('object expected');
      return parsed;
    } catch (_) {
      try { localStorage.setItem(key+'_unreadable_'+Date.now(),raw); } catch (_) {}
      return fallback;
    }
  }
  function loadState() { return {weight:readJson(KEYS.weight,[]).filter(Boolean),exercise:readJson(KEYS.exercise,[]).filter(Boolean),food:readJson(KEYS.food,[]).filter(Boolean),settings:readJson(KEYS.settings,{}),programs:readJson(KEYS.programs,[]).filter(Boolean),mealRoutines:readJson(KEYS.mealRoutines,[]).filter(Boolean)}; }
  var state=loadState();
  function writeJson(key,value) { try{localStorage.setItem(key,JSON.stringify(value));return true;}catch(_){alert('บันทึกไม่สำเร็จ พื้นที่ในเครื่องอาจเต็ม ลองลบรูปอาหารบางรายการหรือส่งออกข้อมูลสำรองก่อน');return false;} }
  function persist(section) { return writeJson(KEYS[section],state[section]); }

  window.openModal=function(id){var el=$(id);if(el)el.classList.add('open');};
  window.closeModal=function(id){var el=$(id);if(el)el.classList.remove('open');};
  function closeAll(){document.querySelectorAll('.modal-overlay.open').forEach(function(el){el.classList.remove('open');});}
  function updateHeader(){if($('headerDate'))$('headerDate').textContent=displayDate(today(),true);}

  window.switchTab=function(tab){currentTab=['today','food','workout','history'].indexOf(tab)>=0?tab:'today';document.querySelectorAll('.nav-item[data-tab]').forEach(function(btn){btn.classList.toggle('active',btn.dataset.tab===currentTab);});renderCurrent();};
  function renderCurrent(){updateHeader();if(currentTab==='food')renderFoodPage();else if(currentTab==='workout')renderWorkoutPage();else if(currentTab==='history')renderHistoryPage('all');else renderTodayPage();}
  function todayFood(){var d=today();return state.food.filter(function(f){return f.date===d;});}
  function todayWorkouts(){var d=today();return state.exercise.filter(function(e){return e.date===d;});}

  function macro(label,icon,color,value,goal){return '<div class="macro-item"><div class="macro-item-header"><span class="macro-icon '+color+'">'+icon+'</span><div><div class="macro-value">'+Math.round(value)+' / '+Math.round(goal)+' g</div><div class="macro-label">'+label+'</div></div></div><div class="macro-bar-bg"><div class="macro-bar-fill '+color+'" style="width:'+pct(value,goal)+'%"></div></div><span class="remaining-tag">เหลือ '+Math.round(Math.max(0,goal-value))+' g</span></div>';}
  function mealList(list,compact){
    if(!list.length)return '<p class="empty-message">ยังไม่มีรายการอาหารในวันนี้</p>';
    var html='',groups=['เช้า','กลางวัน','เย็น','ของว่าง','ก่อนออกกำลัง','หลังออกกำลัง','อื่นๆ'];
    groups.forEach(function(meal){var items=list.filter(function(f){return(f.mealTime||'อื่นๆ')===meal;});if(!items.length)return;html+='<div class="meal-group"><div class="meal-group-header"><span class="meal-time-label">'+esc(meal)+'</span><span class="meal-cal-label">'+Math.round(sum(items,'cal'))+' kcal</span></div>';items.forEach(function(f){html+='<div class="meal-item"><div class="meal-item-info"><div class="meal-item-name">'+esc(f.name||'ไม่ระบุ')+'</div><div class="meal-item-cal">'+num(f.portion,0,null,1)+' '+esc(f.unit||'จาน')+' · '+Math.round(num(f.cal,0,null,0))+' kcal</div></div>'+(compact?'':'<button class="history-item-btn" onclick="openDateShift(\'food\',\''+enc(f.id)+'\')" title="ย้ายวัน">📅</button>')+'<button class="history-item-btn" onclick="openFoodModal(\''+enc(f.id)+'\')" title="แก้ไข">✎</button><button class="history-item-btn danger" onclick="deleteFood(\''+enc(f.id)+'\')" title="ลบ">×</button></div>';});html+='</div>';});return html;
  }

  function renderTodayPage(){
    var foods=todayFood(),workouts=todayWorkouts(),s=state.settings,calories=sum(foods,'cal'),protein=sum(foods,'protein'),carbs=sum(foods,'carbs'),fat=sum(foods,'fat');
    var goalCal=num(s.goalCalories,1,null,2000),goalP=num(s.goalProtein,1,null,130),goalC=num(s.goalCarbs,1,null,220),goalF=num(s.goalFat,1,null,65);
    var latest=state.weight.slice().sort(function(a,b){return dateTimeKey(b).localeCompare(dateTimeKey(a));})[0],start=weekStart(today()),week=state.exercise.filter(function(e){return e.date>=start&&e.date<=today();}),weekMin=sum(week,'duration'),weekGoal=num(s.goalExerciseMinutes,1,null,150),tracked=new Set(state.food.filter(function(f){return f.date>=start&&f.date<=today();}).map(function(f){return f.date;})).size;
    var workoutHtml=workouts.length?workouts.map(function(w){return '<div class="workout-card"><div class="workout-card-top"><div><div class="workout-name">'+esc(w.type||'ออกกำลังกาย')+'</div><div class="workout-duration">'+Math.round(num(w.duration,0,null,0))+' นาที · '+esc(w.intensity||'ปานกลาง')+'</div></div><button class="btn btn-sm" onclick="openWorkoutDetail(\''+enc(w.id)+'\')">ดู</button></div></div>';}).join(''):'<p class="empty-message">วันนี้ยังไม่ได้ออกกำลังกาย</p>';
    $('mainContent').innerHTML='<div class="page active today-page"><div class="page-header"><div><h2 class="page-title">วันนี้</h2><p class="page-subtitle">'+displayDate(today(),true)+'</p></div><button class="btn btn-sm" onclick="openGoalsModal()">🎯 เป้าหมาย</button></div><div class="fast-add-row"><button class="fast-add-btn" onclick="openWeightModal()"><span class="fa-icon">⚖️</span>น้ำหนัก</button><button class="fast-add-btn" onclick="openFoodModal()"><span class="fa-icon">🍽️</span>อาหาร</button><button class="fast-add-btn" onclick="openWorkoutModal()"><span class="fa-icon">🏋️</span>ออกกำลัง</button></div><section class="card summary-card"><div class="summary-title">พลังงานวันนี้</div><div class="calories-big"><div class="calories-left"><div class="calories-value">'+Math.round(calories)+' <span class="kcal-unit">kcal</span></div><div class="calories-target">เป้าหมาย '+Math.round(goalCal)+' · เหลือ '+Math.round(Math.max(0,goalCal-calories))+'</div></div><div class="calories-ring"><svg viewBox="0 0 100 100"><circle class="calories-ring-bg" cx="50" cy="50" r="42"></circle><circle class="calories-ring-fill" cx="50" cy="50" r="42" style="stroke-dasharray:'+(pct(calories,goalCal)*2.64)+' 264"></circle></svg><div class="calories-ring-label"><strong>'+Math.round(pct(calories,goalCal))+'%</strong><span class="remain">ของเป้า</span></div></div></div><div class="macros-grid">'+macro('โปรตีน','P','protein',protein,goalP)+macro('คาร์บ','C','carbs',carbs,goalC)+macro('ไขมัน','F','fat',fat,goalF)+'</div></section><section class="card"><div class="card-header"><h3 class="card-title"><span class="card-icon">⚖️</span>น้ำหนักล่าสุด</h3><button class="card-action" onclick="openWeightModal()">+ บันทึก</button></div>'+(latest?'<div class="weight-highlight"><strong>'+num(latest.value,0,null,0).toFixed(1)+' kg</strong><span>'+displayDate(latest.date)+(latest.note?' · '+esc(latest.note):'')+'</span></div>':'<p class="empty-message">ยังไม่มีข้อมูลน้ำหนัก</p>')+'</section><section class="card"><div class="card-header"><h3 class="card-title"><span class="card-icon">🏋️</span>การออกกำลังวันนี้</h3><button class="card-action" onclick="openWorkoutModal()">+ บันทึก</button></div>'+workoutHtml+'</section><section class="card meals-card"><div class="meals-header"><h3 class="meals-title">🍽️ มื้ออาหารวันนี้</h3><button class="add-meal-btn" onclick="openFoodModal()">+ เพิ่มมื้อ</button></div>'+mealList(foods,true)+'</section><section class="weekly-summary-mini"><div class="weekly-summary-item"><div class="weekly-summary-value">'+weekMin+' / '+weekGoal+'</div><div class="weekly-summary-label">นาทีออกกำลังสัปดาห์นี้</div></div><div class="weekly-summary-item"><div class="weekly-summary-value">'+week.length+'</div><div class="weekly-summary-label">ครั้งที่ออกกำลัง</div></div><div class="weekly-summary-item"><div class="weekly-summary-value">'+tracked+'</div><div class="weekly-summary-label">วันที่บันทึกอาหาร</div></div></section></div>';
  }

  function renderFoodPage(){
    var routines=state.mealRoutines,routineHtml=routines.length?routines.map(function(r){var total=(r.items||[]).reduce(function(n,i){return n+num(i.cal,0,null,0);},0);return '<div class="meal-routine-item"><div class="mr-left" onclick="useMealRoutine(\''+enc(r.id)+'\')"><span class="mr-icon">🍱</span><div><div class="mr-name">'+esc(r.name)+'</div><div class="mr-meal">'+esc(r.mealTime||'อื่นๆ')+'</div></div></div><span class="mr-cal">'+Math.round(total)+' kcal</span><button class="history-item-btn" onclick="openMealRoutineModal(\''+enc(r.id)+'\')">✎</button><button class="history-item-btn danger" onclick="deleteMealRoutine(\''+enc(r.id)+'\')">×</button></div>';}).join(''):'<p class="empty-message">ยังไม่มีมื้อประจำ สร้างไว้สำหรับรายการที่กินบ่อยได้</p>';
    $('mainContent').innerHTML='<div class="page active food-page"><div class="page-header"><div><h2 class="page-title">อาหาร</h2><p class="page-subtitle">บันทึกให้เร็ว ไม่จำเป็นต้องเป๊ะทุกมื้อ</p></div><button class="btn btn-primary" onclick="openFoodModal()">+ เพิ่มอาหาร</button></div><div class="food-search-bar"><input class="food-search-input" id="pageFoodSearch" placeholder="ค้นหาอาหาร แล้วเพิ่มลงมื้อ..."><button class="food-search-btn" onclick="openFoodFromPageSearch()">ค้นหา</button></div><section class="card"><div class="card-header"><h3 class="card-title">🍱 มื้ออาหารประจำ</h3><button class="card-action" onclick="openMealRoutineModal()">+ สร้าง</button></div>'+routineHtml+'</section><section class="card meals-card"><div class="meals-header"><h3 class="meals-title">รายการวันนี้</h3><span class="meal-cal-label">'+Math.round(sum(todayFood(),'cal'))+' kcal</span></div>'+mealList(todayFood(),false)+'</section></div>';
  }
  window.openFoodFromPageSearch=function(){var q=$('pageFoodSearch')?$('pageFoodSearch').value:'';window.openFoodModal();$('foodName').value=q;renderFoodSearch(q);$('foodName').focus();};

  function renderWorkoutPage(){
    var programs=state.programs.length?state.programs.map(function(p){return '<div class="workout-card"><div class="workout-card-top"><div><div class="workout-name">'+esc(p.name)+'</div><div class="workout-duration">'+(p.exercises||[]).length+' ท่า'+(p.note?' · '+esc(p.note):'')+'</div></div><button class="workout-start-btn" onclick="openWorkoutModal(\''+enc(p.id)+'\')"><span class="play-icon">▶</span> เริ่ม</button></div><div class="workout-exercises">'+(p.exercises||[]).map(function(ex,i){return '<div class="workout-exercise-item"><span class="workout-ex-item-num">'+(i+1)+'</span><span class="workout-ex-item-name">'+esc(ex.name)+'</span></div>';}).join('')+'</div><div class="inline-actions"><button class="btn btn-sm" onclick="openProgramModal(\''+enc(p.id)+'\')">แก้ไข</button><button class="btn btn-sm btn-danger" onclick="deleteProgram(\''+enc(p.id)+'\')">ลบ</button></div></div>';}).join(''):'<div class="card"><p class="empty-message">ยังไม่มีโปรแกรมฝึก คุณยังบันทึกการออกกำลังแบบอิสระได้</p></div>';
    var recent=state.exercise.slice().sort(function(a,b){return dateTimeKey(b).localeCompare(dateTimeKey(a));}).slice(0,8),recentHtml=recent.length?recent.map(function(w){return '<div class="history-item" onclick="openWorkoutDetail(\''+enc(w.id)+'\')"><div class="history-item-left"><span class="history-item-date">'+displayDate(w.date)+'</span><span class="history-item-title">'+esc(w.type||'ออกกำลังกาย')+'</span><span class="history-item-detail">'+esc(w.intensity||'')+'</span></div><span class="history-item-value green">'+Math.round(num(w.duration,0,null,0))+' นาที</span></div>';}).join(''):'<p class="empty-message">ยังไม่มีประวัติการออกกำลัง</p>';
    $('mainContent').innerHTML='<div class="page active workout-page"><div class="page-header"><div><h2 class="page-title">ออกกำลังกาย</h2><p class="page-subtitle">เลือกโปรแกรม หรือบันทึกแบบอิสระ</p></div><button class="btn btn-primary" onclick="openWorkoutModal()">+ บันทึก</button></div><div class="workout-projections"><button class="prog-chip active" onclick="openWorkoutModal()"><span class="prog-icon">⚡</span><span class="prog-name">อิสระ</span></button><button class="prog-chip" onclick="openProgramModal()"><span class="prog-icon">＋</span><span class="prog-name">สร้างโปรแกรม</span></button><button class="prog-chip" onclick="openModal(\'restTimerModal\')"><span class="prog-icon">⏱️</span><span class="prog-name">จับเวลาพัก</span></button></div>'+programs+'<section class="card"><div class="card-header"><h3 class="card-title">ประวัติล่าสุด</h3></div><div class="history-list">'+recentHtml+'</div></section></div>';
  }

  var historyFilter='all';
  function renderHistoryPage(filter){
    historyFilter=filter||historyFilter;var items=[];
    state.weight.forEach(function(w){items.push({kind:'weight',id:w.id,date:w.date,time:w.time,title:num(w.value,0,null,0).toFixed(1)+' kg',detail:w.note||'',value:'น้ำหนัก'});});
    state.food.forEach(function(f){items.push({kind:'food',id:f.id,date:f.date,time:f.time,title:f.name||'อาหาร',detail:(f.mealTime||'')+' · '+Math.round(num(f.cal,0,null,0))+' kcal',value:'อาหาร'});});
    state.exercise.forEach(function(w){items.push({kind:'workout',id:w.id,date:w.date,time:w.time,title:w.type||'ออกกำลังกาย',detail:Math.round(num(w.duration,0,null,0))+' นาที · '+(w.intensity||''),value:'ออกกำลัง'});});
    if(historyFilter!=='all')items=items.filter(function(i){return i.kind===historyFilter;});items.sort(function(a,b){return dateTimeKey(b).localeCompare(dateTimeKey(a));});
    var list=items.length?items.map(function(i){var edit=i.kind==='weight'?'openWeightModal':i.kind==='food'?'openFoodModal':'openWorkoutDetail',del=i.kind==='weight'?'deleteWeight':i.kind==='food'?'deleteFood':'deleteWorkoutById',color=i.kind==='weight'?'blue':i.kind==='food'?'orange':'green';return '<div class="history-item"><div class="history-item-left"><span class="history-item-date">'+displayDate(i.date)+(i.time?' · '+esc(i.time):'')+'</span><span class="history-item-title">'+esc(i.title)+'</span><span class="history-item-detail">'+esc(i.detail)+'</span></div><div class="history-item-right"><span class="history-item-value '+color+'">'+i.value+'</span><div class="history-item-actions"><button class="history-item-btn" onclick="'+edit+'(\''+enc(i.id)+'\')">✎</button><button class="history-item-btn" onclick="openDateShift(\''+i.kind+'\',\''+enc(i.id)+'\')">📅</button><button class="history-item-btn danger" onclick="'+del+'(\''+enc(i.id)+'\')">×</button></div></div></div>';}).join(''):'<p class="empty-message">ยังไม่มีข้อมูลในหมวดนี้</p>';
    $('mainContent').innerHTML='<div class="page active history-page"><div class="page-header"><div><h2 class="page-title">ประวัติ</h2><p class="page-subtitle">รวมข้อมูลทั้งหมดในเครื่องนี้</p></div></div><div class="history-nav">'+[['all','ทั้งหมด'],['weight','น้ำหนัก'],['food','อาหาร'],['workout','ออกกำลัง']].map(function(pair){return '<button class="history-nav-btn '+(historyFilter===pair[0]?'active':'')+'" onclick="filterHistory(\''+pair[0]+'\')">'+pair[1]+'</button>';}).join('')+'</div><div class="history-list">'+list+'</div></div>';
  }
  window.filterHistory=function(filter){renderHistoryPage(filter);};

  window.openWeightModal=function(encodedId){var id=encodedId?dec(encodedId):'',r=id?state.weight.find(function(w){return String(w.id)===id;}):null;$('editWeightId').value=r?r.id:'';$('weightValue').value=r?r.value:'';$('weightDate').value=r?r.date:today();$('weightTime').value=r?(r.time||timeNow()):timeNow();$('weightNote').value=r?(r.note||''):'';window.openModal('weightModal');setTimeout(function(){$('weightValue').focus();},0);};
  window.saveWeightRecord=function(){var value=num($('weightValue').value,20,300,null),date=$('weightDate').value;if(value==null||!/^\d{4}-\d{2}-\d{2}$/.test(date))return alert('กรุณากรอกน้ำหนักและวันที่ให้ถูกต้อง');var id=$('editWeightId').value,r=id?state.weight.find(function(w){return String(w.id)===id;}):null;if(!r){r={id:uid('w'),createdAt:Date.now()};state.weight.push(r);}r.value=value;r.date=date;r.time=$('weightTime').value||timeNow();r.note=$('weightNote').value.trim();r.updatedAt=Date.now();if(persist('weight')){window.closeModal('weightModal');renderCurrent();}};
  window.deleteWeight=function(encodedId){var id=dec(encodedId);if(!confirm('ลบบันทึกน้ำหนักรายการนี้?'))return;state.weight=state.weight.filter(function(w){return String(w.id)!==id;});if(persist('weight'))renderCurrent();};

  function resetFood(){ $('editFoodId').value='';$('mealTime').value='เช้า';$('foodName').value='';$('foodPortion').value='1';$('foodPortionUnit').value='จาน';['foodCal','foodProtein','foodCarbs','foodFat'].forEach(function(id){$(id).value='';});$('foodNote').value='';$('foodSearchResults').innerHTML='';$('foodPhotoPreview').innerHTML='';$('saveFoodBtn').textContent='บันทึก';foodPhotoData=null;selectedFoodBase=null; }
  window.openFoodModal=function(encodedId){resetFood();var id=encodedId?dec(encodedId):'',r=id?state.food.find(function(f){return String(f.id)===id;}):null;if(r){$('editFoodId').value=r.id;$('mealTime').value=r.mealTime||'อื่นๆ';$('foodName').value=r.name||'';$('foodPortion').value=r.portion||1;$('foodPortionUnit').value=r.unit||'จาน';$('foodCal').value=r.cal||0;$('foodProtein').value=r.protein||0;$('foodCarbs').value=r.carbs||0;$('foodFat').value=r.fat||0;$('foodNote').value=r.note||'';foodPhotoData=r.photo||null;renderPhoto();$('saveFoodBtn').textContent='บันทึกการแก้ไข';}window.openModal('foodModal');setTimeout(function(){$('foodName').focus();},0);};
  function renderFoodSearch(query){var results=$('foodSearchResults'),q=String(query||'').trim().toLowerCase();if(!q){results.innerHTML='';return;}var matches=(window.FOOD_DB||[]).filter(function(f){return String(f.name).toLowerCase().indexOf(q)>=0;}).slice(0,12);window.__foodMatches=matches;results.innerHTML=matches.length?matches.map(function(f,i){return '<button type="button" class="food-result" onclick="selectFoodResult('+i+')"><strong>'+esc(f.name)+'</strong><small>'+esc(f.per||'ต่อหนึ่งหน่วย')+' · ประมาณ '+Math.round(f.cal)+' kcal</small></button>';}).join(''):'<div class="no-results">ไม่พบในรายการ คุณยังกรอกชื่อและสารอาหารเองได้</div>';}
  window.selectFoodResult=function(index){var f=(window.__foodMatches||[])[index];if(!f)return;selectedFoodBase={cal:f.cal,protein:f.protein,carbs:f.carbs,fat:f.fat};$('foodName').value=f.name;$('foodPortion').value=1;updateFoodPortion();$('foodSearchResults').innerHTML='';};
  function updateFoodPortion(){if(!selectedFoodBase)return;var p=num($('foodPortion').value,.1,20,1);$('foodCal').value=+(selectedFoodBase.cal*p).toFixed(1);$('foodProtein').value=+(selectedFoodBase.protein*p).toFixed(1);$('foodCarbs').value=+(selectedFoodBase.carbs*p).toFixed(1);$('foodFat').value=+(selectedFoodBase.fat*p).toFixed(1);}
  window.saveFood=function(){var name=$('foodName').value.trim(),cal=num($('foodCal').value,0,5000,null);if(!name||cal==null)return alert('กรุณากรอกชื่ออาหารและแคลอรี่');var id=$('editFoodId').value,r=id?state.food.find(function(f){return String(f.id)===id;}):null;if(!r){r={id:uid('f'),date:today(),time:timeNow(),createdAt:Date.now()};state.food.push(r);}r.mealTime=$('mealTime').value;r.name=name;r.portion=num($('foodPortion').value,.1,20,1);r.unit=$('foodPortionUnit').value;r.cal=cal;r.protein=num($('foodProtein').value,0,500,0);r.carbs=num($('foodCarbs').value,0,500,0);r.fat=num($('foodFat').value,0,200,0);r.note=$('foodNote').value.trim();r.photo=foodPhotoData;r.updatedAt=Date.now();if(persist('food')){window.closeModal('foodModal');renderCurrent();}};
  window.deleteFood=function(encodedId){var id=dec(encodedId);if(!confirm('ลบรายการอาหารนี้?'))return;state.food=state.food.filter(function(f){return String(f.id)!==id;});if(persist('food'))renderCurrent();};
  function renderPhoto(){$('foodPhotoPreview').innerHTML=foodPhotoData?'<div class="photo-preview thumb"><img src="'+foodPhotoData+'" alt="รูปอาหาร"><button class="remove-photo" type="button" onclick="removeFoodPhoto()">×</button></div>':'';}
  window.removeFoodPhoto=function(){foodPhotoData=null;$('foodPhotoInput').value='';renderPhoto();};
  window.handleFoodPhotoSelect=function(event){var file=event.target.files&&event.target.files[0];if(!file)return;if(!file.type.startsWith('image/'))return alert('กรุณาเลือกไฟล์รูปภาพ');var reader=new FileReader();reader.onload=function(ev){var image=new Image();image.onload=function(){var scale=Math.min(1,900/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);foodPhotoData=canvas.toDataURL('image/jpeg',.72);renderPhoto();};image.src=ev.target.result;};reader.readAsDataURL(file);};

  window.openWorkoutModal=function(encodedProgramId,encodedWorkoutId){
    var pid=encodedProgramId?dec(encodedProgramId):'',wid=encodedWorkoutId?dec(encodedWorkoutId):'',p=pid?state.programs.find(function(x){return String(x.id)===pid;}):null,w=wid?state.exercise.find(function(x){return String(x.id)===wid;}):null;
    $('workoutModalTitle').textContent=w?'แก้ไขการออกกำลังกาย':p?'เริ่ม '+p.name:'บันทึกการออกกำลังกาย';
    $('workoutModalBody').innerHTML='<input type="hidden" id="editWorkoutId" value="'+esc(w?w.id:'')+'"><div class="form-row"><div class="form-group"><label>วันที่</label><input type="date" class="form-input" id="workoutDate" value="'+esc(w?w.date:today())+'"></div><div class="form-group"><label>เวลา</label><input type="time" class="form-input" id="workoutTime" value="'+esc(w?(w.time||timeNow()):timeNow())+'"></div></div><div class="form-group"><label>ชื่อการฝึก</label><input class="form-input" id="workoutName" value="'+esc(w?w.type:p?p.name:'')+'" placeholder="เช่น วิ่ง, Push Day"></div><div class="form-row"><div class="form-group"><label>ระยะเวลา (นาที)</label><input type="number" class="form-input" id="workoutDuration" min="1" max="600" value="'+esc(w?w.duration:'')+'"></div><div class="form-group"><label>ความหนัก</label><select class="form-select" id="workoutIntensity"><option value="เบา">เบา</option><option value="ปานกลาง">ปานกลาง</option><option value="หนัก">หนัก</option></select></div></div><div class="form-group"><div class="card-header"><label>ท่าฝึก / เซต</label><button class="btn btn-sm" type="button" onclick="addWorkoutSet()">+ เพิ่มท่า</button></div><div id="workoutSetRows"></div></div><div class="form-group"><label>หมายเหตุ</label><textarea class="form-textarea" id="workoutNote">'+esc(w?(w.note||''):'')+'</textarea></div>';
    $('workoutIntensity').value=w?(w.intensity||'ปานกลาง'):'ปานกลาง';var sets=w?(w.sets||[]):p?(p.exercises||[]).map(function(ex){return{exercise:ex.name,sets:ex.sets||3,reps:ex.reps||10,weight:ex.weight||0};}):[];sets.forEach(addWorkoutSetRow);$('workoutModalSaveBtn').style.display='';window.openModal('workoutModal');
  };
  function addWorkoutSetRow(set){var row=document.createElement('div');row.className='workout-set-row';row.innerHTML='<input class="form-input set-name" placeholder="ชื่อท่า" value="'+esc(set&&(set.exercise||set.name)||'')+'"><input type="number" class="form-input set-count" min="1" max="20" placeholder="เซต" value="'+esc(set&&set.sets||3)+'"><input type="number" class="form-input set-reps" min="1" max="200" placeholder="ครั้ง" value="'+esc(set&&set.reps||10)+'"><input type="number" class="form-input set-weight" min="0" max="1000" step="0.5" placeholder="kg" value="'+esc(set&&set.weight||'')+'"><button class="history-item-btn danger" type="button">×</button>';row.querySelector('button').addEventListener('click',function(){row.remove();});$('workoutSetRows').appendChild(row);}
  window.addWorkoutSet=function(){addWorkoutSetRow({});};
  window.saveWorkoutLog=function(){var name=$('workoutName').value.trim(),duration=num($('workoutDuration').value,1,600,null),date=$('workoutDate').value;if(!name||duration==null||!/^\d{4}-\d{2}-\d{2}$/.test(date))return alert('กรุณากรอกชื่อ ระยะเวลา และวันที่');var sets=Array.from(document.querySelectorAll('#workoutSetRows .workout-set-row')).map(function(row){return{exercise:row.querySelector('.set-name').value.trim(),sets:num(row.querySelector('.set-count').value,1,20,1),reps:num(row.querySelector('.set-reps').value,1,200,1),weight:num(row.querySelector('.set-weight').value,0,1000,0)};}).filter(function(set){return set.exercise;}),id=$('editWorkoutId').value,r=id?state.exercise.find(function(x){return String(x.id)===id;}):null;if(!r){r={id:uid('e'),createdAt:Date.now()};state.exercise.push(r);}r.date=date;r.time=$('workoutTime').value||timeNow();r.type=name;r.duration=duration;r.intensity=$('workoutIntensity').value;r.sets=sets;r.note=$('workoutNote').value.trim();r.updatedAt=Date.now();if(persist('exercise')){window.closeModal('workoutModal');renderCurrent();}};
  window.openWorkoutDetail=function(encodedId){var id=dec(encodedId),w=state.exercise.find(function(x){return String(x.id)===id;});if(!w)return;activeWorkoutId=id;var sets=w.sets||[];$('workoutDetailBody').innerHTML='<div class="detail-hero"><strong>'+esc(w.type||'ออกกำลังกาย')+'</strong><span>'+displayDate(w.date)+' · '+esc(w.time||'')+'</span><span>'+Math.round(num(w.duration,0,null,0))+' นาที · '+esc(w.intensity||'')+'</span></div>'+(sets.length?'<div class="workout-detail-sets">'+sets.map(function(set,i){return '<div><span>'+(i+1)+'. '+esc(set.exercise||set.name||'ท่า')+'</span><strong>'+num(set.sets,1,null,1)+' × '+num(set.reps,1,null,1)+(num(set.weight,0,null,0)?' @ '+set.weight+' kg':'')+'</strong></div>';}).join('')+'</div>':'')+(w.note?'<p class="settings-note">'+esc(w.note)+'</p>':'')+'<div class="inline-actions"><button class="btn btn-sm" onclick="closeModal(\'workoutDetailModal\');openWorkoutModal(\'\',\''+enc(w.id)+'\')">แก้ไข</button><button class="btn btn-sm" onclick="closeModal(\'workoutDetailModal\');openDateShift(\'workout\',\''+enc(w.id)+'\')">ย้ายวัน</button></div>';window.openModal('workoutDetailModal');};
  window.deleteWorkoutLog=function(){if(activeWorkoutId)window.deleteWorkoutById(enc(activeWorkoutId));};
  window.deleteWorkoutById=function(encodedId){var id=dec(encodedId);if(!confirm('ลบบันทึกการออกกำลังนี้?'))return;state.exercise=state.exercise.filter(function(w){return String(w.id)!==id;});if(persist('exercise')){window.closeModal('workoutDetailModal');activeWorkoutId=null;renderCurrent();}};

  window.openProgramModal=function(encodedId){var id=encodedId?dec(encodedId):'',p=id?state.programs.find(function(x){return String(x.id)===id;}):null;$('editProgramId').value=p?p.id:'';$('programName').value=p?p.name:'';$('programNote').value=p?(p.note||''):'';programDraft=p?JSON.parse(JSON.stringify(p.exercises||[])):[];$('programModalTitle').textContent=p?'แก้ไขโปรแกรมฝึก':'สร้างโปรแกรมฝึก';renderProgramDraft();window.openModal('programModal');};
  function renderProgramDraft(){$('programExercisesList').innerHTML=programDraft.length?programDraft.map(function(ex,i){return '<div class="draft-item"><span>'+(i+1)+'. '+esc(ex.name)+'</span><button type="button" onclick="removeProgramExercise('+i+')">×</button></div>';}).join(''):'<p class="empty-message">ยังไม่มีท่าฝึก</p>';}
  window.addProgramExercise=function(){var name=$('programExerciseName').value.trim();if(!name)return;programDraft.push({name:name,sets:3,reps:10,weight:0});$('programExerciseName').value='';renderProgramDraft();};window.removeProgramExercise=function(i){programDraft.splice(i,1);renderProgramDraft();};
  window.saveProgram=function(){var name=$('programName').value.trim();if(!name||!programDraft.length)return alert('กรุณาตั้งชื่อและเพิ่มอย่างน้อย 1 ท่า');var id=$('editProgramId').value,p=id?state.programs.find(function(x){return String(x.id)===id;}):null;if(!p){p={id:uid('p'),createdAt:Date.now()};state.programs.push(p);}p.name=name;p.note=$('programNote').value.trim();p.exercises=programDraft.slice();p.updatedAt=Date.now();if(persist('programs')){window.closeModal('programModal');renderCurrent();}};
  window.deleteProgram=function(encodedId){var id=dec(encodedId);if(!confirm('ลบโปรแกรมฝึกนี้? ประวัติการฝึกจะไม่ถูกลบ'))return;state.programs=state.programs.filter(function(p){return String(p.id)!==id;});if(persist('programs'))renderCurrent();};

  window.openMealRoutineModal=function(encodedId){var id=encodedId?dec(encodedId):'',r=id?state.mealRoutines.find(function(x){return String(x.id)===id;}):null;$('editMealRoutineId').value=r?r.id:'';$('mealRoutineName').value=r?r.name:'';$('mealRoutineMealTime').value=r?(r.mealTime||'เช้า'):'เช้า';mealRoutineDraft=r?JSON.parse(JSON.stringify(r.items||[])):[];$('mealRoutineModalTitle').textContent=r?'แก้ไขมื้ออาหารประจำ':'สร้างมื้ออาหารประจำ';renderMealDraft();window.openModal('mealRoutineModal');};
  function renderMealDraft(){$('mealRoutineItems').innerHTML=mealRoutineDraft.length?mealRoutineDraft.map(function(item,i){return '<div class="draft-item"><span>'+esc(item.name)+' · '+Math.round(num(item.cal,0,null,0))+' kcal</span><button type="button" onclick="removeMealRoutineItem('+i+')">×</button></div>';}).join(''):'<p class="empty-message">ยังไม่มีรายการในมื้อนี้</p>';}
  window.addMealRoutineItem=function(){var name=$('mealRoutineFoodName').value.trim(),cal=num($('mealRoutineFoodCal').value,0,5000,null);if(!name||cal==null)return;mealRoutineDraft.push({name:name,cal:cal});$('mealRoutineFoodName').value='';$('mealRoutineFoodCal').value='';renderMealDraft();};window.removeMealRoutineItem=function(i){mealRoutineDraft.splice(i,1);renderMealDraft();};
  window.saveMealRoutine=function(){var name=$('mealRoutineName').value.trim();if(!name||!mealRoutineDraft.length)return alert('กรุณาตั้งชื่อและเพิ่มอาหารอย่างน้อย 1 รายการ');var id=$('editMealRoutineId').value,r=id?state.mealRoutines.find(function(x){return String(x.id)===id;}):null;if(!r){r={id:uid('mr'),createdAt:Date.now()};state.mealRoutines.push(r);}r.name=name;r.mealTime=$('mealRoutineMealTime').value;r.items=mealRoutineDraft.slice();r.updatedAt=Date.now();if(persist('mealRoutines')){window.closeModal('mealRoutineModal');renderCurrent();}};
  window.deleteMealRoutine=function(encodedId){var id=dec(encodedId);if(!confirm('ลบมื้ออาหารประจำนี้?'))return;state.mealRoutines=state.mealRoutines.filter(function(r){return String(r.id)!==id;});if(persist('mealRoutines'))renderCurrent();};
  window.useMealRoutine=function(encodedId){var id=dec(encodedId),r=state.mealRoutines.find(function(x){return String(x.id)===id;});if(!r||!r.items.length)return;state.food.push({id:uid('f'),date:today(),time:timeNow(),mealTime:r.mealTime||'อื่นๆ',name:r.items.map(function(i){return i.name;}).join(' + '),portion:1,unit:'มื้อ',cal:r.items.reduce(function(n,i){return n+num(i.cal,0,null,0);},0),protein:0,carbs:0,fat:0,note:'จากมื้อประจำ: '+r.name,createdAt:Date.now()});if(persist('food'))renderCurrent();};

  window.openDateShift=function(kind,encodedId){shiftContext={kind:kind,id:dec(encodedId)};var list=kind==='weight'?state.weight:kind==='food'?state.food:state.exercise,r=list.find(function(x){return String(x.id)===shiftContext.id;});if(!r)return;$('dateShiftTarget').value=r.date||today();$('dateShiftNote').value='';window.openModal('dateShiftModal');};
  window.confirmDateShift=function(){if(!shiftContext)return;var section=shiftContext.kind==='weight'?'weight':shiftContext.kind==='food'?'food':'exercise',r=state[section].find(function(x){return String(x.id)===shiftContext.id;}),date=$('dateShiftTarget').value;if(!r||!/^\d{4}-\d{2}-\d{2}$/.test(date))return alert('กรุณาเลือกวันที่');r.date=date;var note=$('dateShiftNote').value.trim();if(note)r.note=[r.note,note].filter(Boolean).join(' · ');r.updatedAt=Date.now();if(persist(section)){window.closeModal('dateShiftModal');shiftContext=null;renderCurrent();}};

  function populateSettings(){var s=state.settings;['goalCalories','goalProtein','goalCarbs','goalFat','goalWeight','goalDate','goalExerciseMinutes','goalExerciseDays','goalType'].forEach(function(id){if($(id))$(id).value=s[id]==null?'':s[id];});}
  window.saveSettings=function(){var s=state.settings;s.goalCalories=num($('goalCalories').value,500,10000,2000);s.goalProtein=num($('goalProtein').value,0,300,130);s.goalCarbs=num($('goalCarbs').value,0,500,220);s.goalFat=num($('goalFat').value,0,200,65);s.goalWeight=num($('goalWeight').value,20,300,null);s.goalDate=$('goalDate').value;s.goalType=$('goalType').value;s.goalExerciseMinutes=num($('goalExerciseMinutes').value,0,1000,150);s.goalExerciseDays=num($('goalExerciseDays').value,0,14,3);if(persist('settings')){window.closeModal('settingsModal');renderCurrent();}};
  window.openGoalsModal=function(){var s=state.settings;$('goalName').value=s.goalName||'';$('goalTargetWeight').value=s.goalWeight||'';$('goalTargetDate').value=s.goalDate||'';$('goalTargetType').value=s.goalType||'maintain';$('goalTargetCal').value=s.goalCalories||2000;$('goalTargetProtein').value=s.goalProtein||130;$('goalTargetCarbs').value=s.goalCarbs||220;$('goalTargetFat').value=s.goalFat||65;$('goalTargetMinutes').value=s.goalExerciseMinutes||150;$('goalTargetDays').value=s.goalExerciseDays||3;window.openModal('goalsModal');};
  window.saveGoals=function(){var s=state.settings;s.goalName=$('goalName').value.trim();s.goalWeight=num($('goalTargetWeight').value,20,300,null);s.goalDate=$('goalTargetDate').value;s.goalType=$('goalTargetType').value;s.goalCalories=num($('goalTargetCal').value,500,10000,2000);s.goalProtein=num($('goalTargetProtein').value,0,300,130);s.goalCarbs=num($('goalTargetCarbs').value,0,500,220);s.goalFat=num($('goalTargetFat').value,0,200,65);s.goalExerciseMinutes=num($('goalTargetMinutes').value,0,1000,150);s.goalExerciseDays=num($('goalTargetDays').value,0,14,3);if(persist('settings')){populateSettings();window.closeModal('goalsModal');renderCurrent();}};

  window.timerSet=function(s){timerSeconds=s;renderTimer();};window.timerStart=function(){if(timerHandle||timerSeconds<=0)return;$('timerStartBtn').style.display='none';$('timerPauseBtn').style.display='';timerHandle=setInterval(function(){timerSeconds--;renderTimer();if(timerSeconds<=0){window.timerPause();if(navigator.vibrate)navigator.vibrate([200,100,200]);}},1000);};window.timerPause=function(){if(timerHandle)clearInterval(timerHandle);timerHandle=null;$('timerStartBtn').style.display='';$('timerPauseBtn').style.display='none';};window.timerReset=function(){window.timerPause();timerSeconds=0;renderTimer();};function renderTimer(){$('timerDisplay').textContent=Math.floor(timerSeconds/60)+':'+String(timerSeconds%60).padStart(2,'0');}

  window.exportData=function(){var backup={schemaVersion:1,exportedAt:new Date().toISOString(),weight:state.weight,exercise:state.exercise,food:state.food,settings:state.settings,programs:state.programs,mealRoutines:state.mealRoutines},blob=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='health-tracker-backup-'+today()+'.json';link.click();setTimeout(function(){URL.revokeObjectURL(url);},1000);};
  window.importData=function(file){if(!file)return;var reader=new FileReader();reader.onload=function(event){try{var data=JSON.parse(event.target.result);if(!data||typeof data!=='object')throw new Error('รูปแบบไฟล์ไม่ถูกต้อง');if(!['weight','exercise','food','settings','programs','mealRoutines'].some(function(k){return Object.prototype.hasOwnProperty.call(data,k);}))throw new Error('ไม่พบข้อมูล Health Tracker ในไฟล์นี้');if(!confirm('การนำเข้าจะแทนที่ข้อมูลในเครื่องนี้ ควรส่งออกข้อมูลเดิมก่อน ต้องการดำเนินการต่อไหม?'))return;state.weight=Array.isArray(data.weight)?data.weight.filter(Boolean):[];state.exercise=Array.isArray(data.exercise)?data.exercise.filter(Boolean):[];state.food=Array.isArray(data.food)?data.food.filter(Boolean):[];state.settings=data.settings&&typeof data.settings==='object'&&!Array.isArray(data.settings)?data.settings:{};state.programs=Array.isArray(data.programs)?data.programs.filter(Boolean):[];state.mealRoutines=Array.isArray(data.mealRoutines)?data.mealRoutines.filter(Boolean):(Array.isArray(data.routines)?data.routines.filter(Boolean):[]);Object.keys(KEYS).forEach(persist);populateSettings();closeAll();renderCurrent();alert('นำเข้าข้อมูลสำเร็จ');}catch(error){alert('นำเข้าไม่สำเร็จ: '+error.message);}};reader.readAsText(file);};
  window.resetAllData=function(){if(!confirm('ล้างข้อมูลน้ำหนัก อาหาร ออกกำลัง โปรแกรม และการตั้งค่าทั้งหมดในเครื่องนี้? การกระทำนี้ย้อนกลับไม่ได้'))return;Object.keys(KEYS).forEach(function(k){localStorage.removeItem(KEYS[k]);});state=loadState();populateSettings();closeAll();window.switchTab('today');};

  document.querySelectorAll('.modal-overlay').forEach(function(modal){modal.addEventListener('click',function(event){if(event.target===modal)window.closeModal(modal.id);});});
  document.addEventListener('keydown',function(event){if(event.key==='Escape')closeAll();});
  $('foodName').addEventListener('input',function(event){selectedFoodBase=null;renderFoodSearch(event.target.value);});
  $('foodPortion').addEventListener('input',updateFoodPortion);
  populateSettings();updateHeader();window.switchTab('today');
})();
